<center style="font-weight: bold;">

<span style="font-size:40px;">
Deep Learning for Computer Vision
</span>
<br>
http://deeplearningforcomputervision.com/

<br><br>

<span style="font-size:20px;">
An Introduction to Python
</span>

<br><br>

<span style="font-size:20px;">
Yogesh Garg
</span>
<br>
Jan 26, 2017
<br>
</center>

**Contents**

<div id="toc"><ul class="toc"><li><a href="#About">I. About</a><a class="anchor-link" href="#About">¶</a></li><li><a href="#Installation">II. Installation</a><a class="anchor-link" href="#Installation">¶</a></li><ul class="toc"><li><a href="#Issues">I. Issues</a><a class="anchor-link" href="#Issues">¶</a></li><li><a href="#Steps">II. Steps</a><a class="anchor-link" href="#Steps">¶</a></li><li><a href="#Homebrew">III. Homebrew</a><a class="anchor-link" href="#Homebrew">¶</a></li><li><a href="#VirtualEnv">IV. VirtualEnv</a><a class="anchor-link" href="#VirtualEnv">¶</a></li><li><a href="#Pip">V. Pip</a><a class="anchor-link" href="#Pip">¶</a></li></ul><li><a href="#Python-Basics">III. Python Basics</a><a class="anchor-link" href="#Python-Basics">¶</a></li><ul class="toc"><li><a href="#Integers,-Float,-Lists">I. Integers, Float, Lists</a><a class="anchor-link" href="#Integers,-Float,-Lists">¶</a></li><li><a href="#Strings,-Multiline-Strings,-Slicing">II. Strings, Multiline Strings, Slicing</a><a class="anchor-link" href="#Strings,-Multiline-Strings,-Slicing">¶</a></li><li><a href="#Control-Flow">III. Control Flow</a><a class="anchor-link" href="#Control-Flow">¶</a></li><li><a href="#Exception-Handling-and-Assertions">IV. Exception Handling and Assertions</a><a class="anchor-link" href="#Exception-Handling-and-Assertions">¶</a></li><li><a href="#Containers">V. Containers</a><a class="anchor-link" href="#Containers">¶</a></li><ul class="toc"><li><a href="#Sets">I. Sets</a><a class="anchor-link" href="#Sets">¶</a></li><li><a href="#Dictionaries">II. Dictionaries</a><a class="anchor-link" href="#Dictionaries">¶</a></li><li><a href="#More-from-Collections">III. More from Collections</a><a class="anchor-link" href="#More-from-Collections">¶</a></li></ul><li><a href="#Functions,-Lambdas">VI. Functions, Lambdas</a><a class="anchor-link" href="#Functions,-Lambdas">¶</a></li><li><a href="#Classes">VII. Classes</a><a class="anchor-link" href="#Classes">¶</a></li><li><a href="#Best-Practices">VIII. Best Practices</a><a class="anchor-link" href="#Best-Practices">¶</a></li><ul class="toc"><li><a href="#Git">I. Git</a><a class="anchor-link" href="#Git">¶</a></li><li><a href="#Logging">II. Logging</a><a class="anchor-link" href="#Logging">¶</a></li></ul></ul><li><a href="#Numpy-Basics">IV. Numpy Basics</a><a class="anchor-link" href="#Numpy-Basics">¶</a></li><ul class="toc"><li><a href="#Arrays">I. Arrays</a><a class="anchor-link" href="#Arrays">¶</a></li><ul class="toc"><li><a href="#Vectors">I. Vectors</a><a class="anchor-link" href="#Vectors">¶</a></li><li><a href="#Matrices">II. Matrices</a><a class="anchor-link" href="#Matrices">¶</a></li></ul><li><a href="#Some-Numpy-Functions">II. Some Numpy Functions</a><a class="anchor-link" href="#Some-Numpy-Functions">¶</a></li><li><a href="#Utility-function-to-inspect-numpy-variables">III. Utility function to inspect numpy variables</a><a class="anchor-link" href="#Utility-function-to-inspect-numpy-variables">¶</a></li><li><a href="#Numpy-Types">IV. Numpy Types</a><a class="anchor-link" href="#Numpy-Types">¶</a></li><li><a href="#Slicing">V. Slicing</a><a class="anchor-link" href="#Slicing">¶</a></li><ul class="toc"><li><a href="#Single-row-or-col-as-a-row">I. Single row or col as a row</a><a class="anchor-link" href="#Single-row-or-col-as-a-row">¶</a></li><li><a href="#Multiple-rows-or-cols-as-a-mat">II. Multiple rows or cols as a mat</a><a class="anchor-link" href="#Multiple-rows-or-cols-as-a-mat">¶</a></li><li><a href="#Slicing-using-lists">III. Slicing using lists</a><a class="anchor-link" href="#Slicing-using-lists">¶</a></li><li><a href="#Slice-as-an-object">IV. Slice as an object</a><a class="anchor-link" href="#Slice-as-an-object">¶</a></li><li><a href="#Slicing-using-indices">V. Slicing using indices</a><a class="anchor-link" href="#Slicing-using-indices">¶</a></li></ul><li><a href="#Axes">VI. Axes</a><a class="anchor-link" href="#Axes">¶</a></li><li><a href="#Broadcasting">VII. Broadcasting</a><a class="anchor-link" href="#Broadcasting">¶</a></li><li><a href="#What-happened?">VIII. What happened?</a><a class="anchor-link" href="#What-happened?">¶</a></li></ul><li><a href="#References">V. References</a><a class="anchor-link" href="#References">¶</a></li></ul></div>

<!--script type="text/javascript" src="https://raw.github.com/kmahelona/ipython_notebook_goodies/master/ipython_notebook_toc.js"-->

# About
This Notebook aims to give a refersher in Python. It talks about various issues, best practices, and a few tricks that have earlier proven to be useful. It also provides a few cookbook style code snippets to allow you to start using certain features faster.


# Installation
## Issues

* It is a good idea to keep your working version of Python independent of the version that your system uses
* Depending on your project, you may wanna use python2.6 or python2.7
* You may want to install different packages or same packages with different versions for different projects
* These changes could interfere with the system and/or make it slower
* Rule of thumb: you should not have to ```sudo```
* Follow the installation steps from a good source, like, [The Hitchhiker’s Guide to Python!] > [Properly Installing Python]
[The Hitchhiker’s Guide to Python!]: http://docs.python-guide.org/en/latest/
[Properly Installing Python]: http://docs.python-guide.org/en/latest/starting/installation/


## Steps
We follow the steps for [Installing Python on Mac OS X](http://docs.python-guide.org/en/latest/starting/install/osx/)

``` bash
# Install **Homebrew**
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Setup path to ensure brew is executable
# Also goes in .bashrc, .profile, or .bash_profile
export PATH=/usr/local/bin:/usr/local/sbin:$PATH

# Install Python
brew install python
# Ensure you have **Pip** also installed
which python
which pip

# Install **VirtualEnv**
pip install virtualenv

# setup directories and coding environment
mkdir -p ~/code/dlforcv/
cd ~/code/dlforcv/
mkdir data                 # for data
mkdir archive              # for zip files
mkdir docs                 # for documents
mkdir src                  # for working code files
mkdir scripts              # for scripts to run code, setup environment etc
virtualenv venv            # this will contain all your packages etc
source venv/bin/activate   # (venv) suffix is added to your prompt
which python               # should refer to python in ~/code/dlforcv/venv/bin
which pip                  # should refer to pip in ~/code/dlforcv/venv/bin

# install requirements
pip install numpy
pip install -r requirements.txt

# start coding!
echo "print 'Hello World!'" > src/hw.py
python src/hw.py

# Run this notebook in ipython/jupyter notebook
pip install ipython notebook

# download this notebook from source to ~/code/dlforcv/scripts/dlforcv-python.ipynb
ipython notebook                    # starts a server, opens a browser

# navigate to scripts, and open this dlforcv-python.ipynb
```

## Homebrew
[Homebrew] manages your packages for you -- including python, many other packages used by developers
## VirtualEnv
[VirtualEnv] allows you to manage different requirements for different projects
## Pip
[Pip] helps you Properly Install Python

[Homebrew]: http://brew.sh/
[VirtualEnv]: http://docs.python-guide.org/en/latest/dev/virtualenvs/#virtualenvironments-ref
[Pip]: http://docs.python-guide.org/en/latest/starting/installation/



# Python Basics

It is recommended to go through sections 3-9 from [The Python Tutorial]. You should be familiar with the following concepts:
[The Python Tutorial]: https://docs.python.org/2.7/tutorial/


## Integers, Float, Lists
* You have ints, floats
* Notice the **list comprehension** syntax
* You also have support for lists
    - add
    - extend
    - pop
* pay attention to list referencing and copying
* ```==``` checks for equality
* ```is``` checks for identity

In [1]:
a = 10
b = 3.14
l = [x**2 for x in range(1,4)]
l.append(a)
l.extend([a*2])

l2 = l
l3 = list(l)
print l
print l2
print l3
print l == l2
print l is l2
print l == l3
print l is l3

l2.pop()
print l
print l2
print l3
print l == l2
print l is l2
print l == l3
print l is l3

[1, 4, 9, 10, 20]
[1, 4, 9, 10, 20]
[1, 4, 9, 10, 20]
True
True
True
False
[1, 4, 9, 10]
[1, 4, 9, 10]
[1, 4, 9, 10, 20]
True
True
False
False


## Strings, Multiline Strings, Slicing

In [2]:
s1 = 'Hello World'
s2 = '''
Hello
World
'''
print str((s1[:5], s1[-5:]))

('Hello', 'World')


## Control Flow

In [3]:
(a,b)=(10,3.15)

if(a<b):
    print 'Case 1'
elif (a>b):
    print 'Case 2'
else: # a==b
    print 'Case 3'

l = [1,2]
for x in l:
    print x

s1 = "HW"
for i,c in enumerate(s1):
    print i,c

while(True):
    print 'inside loop'
    break


Case 2
1
2
0 H
1 W
inside loop


## Exception Handling and Assertions

In [4]:
try:
    print 'before error'
    raise ValueError('ab')
    print 'after error'
except Exception as e:
    print 'handle error'
    pass

print 'asserting 1==1.0'
assert 1==1.0
print 'asserting 1==1.00000001'
try:
    assert 1==1.00000001
except Exception as e:
    print 'assertion failed'

before error
handle error
asserting 1==1.0
asserting 1==1.00000001
assertion failed


## Containers

* Some basic containers include Lists, Dictionaries, Sets
* Advanced containers can be found in [collections module]

[Collections module]: https://docs.python.org/2/library/collections.html

In [5]:
from collections import defaultdict, Counter, OrderedDict

### Sets
 * you can add or remove items from a set
 * if set contains an element, adding it again does not make a difference

In [6]:
s = set([1,2,3])
s.add(4)
s.add(1)
s.remove(1)
print s
print ((1 in s), (2 in s))
s.clear()

set([2, 3, 4])
(False, True)


### Dictionaries
* Notice the very useful **dictionary comprehension** notation
* following operations are supported:
    - get_item
    - set_item
    - has_key
    - (safe) get (None or default value)

In [7]:
d1 = {str(i):i for i in range(3)}
d1['alpha'] = 1
d1.has_key('beta')
try:
    print d1['alpha']
    print d1['beta']
except Exception as e:
    print type(e), e
d1['gamma'] = 2
print d1.get('beta')
print d1.get('beta', -1)
print d1

1
<type 'exceptions.KeyError'> 'beta'
None
-1
{'1': 1, '0': 0, '2': 2, 'gamma': 2, 'alpha': 1}


### More from Collections
 * defaultdict creates an object when a key is first accessed (get_item/set_item)
 * Counter can be used to count occurences of keys
 * OrderedDict preserves the **sequence in which keys were added**

In [8]:
dd = defaultdict(str)
dd['a'] = 'wassup'
print dd
print 'a:', dd['a']
print 'b:', dd['b']
print dd

defaultdict(<type 'str'>, {'a': 'wassup'})
a: wassup
b: 
defaultdict(<type 'str'>, {'a': 'wassup', 'b': ''})


In [9]:
c = Counter()
c['a']+=1
print c['a']
print c['b']

1
0


In [10]:
d2 = OrderedDict()
d2['alpha'] = 1
d2['gamma'] = 2
d2['beta'] = 3
print d2

OrderedDict([('alpha', 1), ('gamma', 2), ('beta', 3)])


## Functions, Lambdas

* Lambdas are just single-statement functions that return something
* useful for [functional programming] -- map, reduce, filter

[functional programming]: https://docs.python.org/2/tutorial/datastructures.html#functional-programming-tools

In [11]:
def f1(a):
    print '\tprinting inside function', a
    return a**2

f2 = lambda x: x**2

print f1(2)
print f2(2)

l1 = range(10)
print map(f2, l1)

	printing inside function 2
4
4
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


## Classes

In the following example,
* ```MyClass1``` is a sub-class of ```object```
* ```__init__``` is the constructor
* ```alpha``` is a 'public' member variable
* ```_beta``` is a 'private' member variable
* ```setBeta``` and ```getAlphaBeta``` are class functions

In [12]:
class MyClass1(object):
    """this is the doc string
    provide more information here"""
    
    def __init__(self, a1, b1=0):
        """
        :param a1: int
        value for alpha
        
        :param b1: int
        value for beta
        """
        assert type(a1) == int
        assert type(b1) == int
        self.alpha = a1
        self._beta = b1
        return
    
    def setBeta(self, b):
        """
        :param b: int
        value for beta
        """
        self._beta = b
        return

    def getAlphaBeta(self):
        return self.alpha * self._beta

# end My Class


Some advice,
* _Just because you could, does not mean you should_
    - You could have functions in a class that do not have a ```self``` parameter
    - You could define member outside the constructor
* always have a return statement in your functions, helps to see where a function ends
* document parameter types for your own sanity
* if you need to take it one step further, check types in the begining of your function
* in ipython, check document strings using '?'
```python
o1 = MyClass1?
o1.setBeta?
```

In [13]:
o1 = MyClass1(2)
print o1.alpha
print o1.getAlphaBeta()
o1.setBeta(1)
print o1.getAlphaBeta()


2
0
2


## Best Practices

* if name is main
    - in a python file (.py), you should only define functions and classes
    - No code should be executed
    - How do I run code then?
        ``` python
        #!/usr/bin/python
        # contents of sample.py
        
        class C1():
            def __init__(self):
                self.c=0
                return
            def f1(self):
                self.c+=1
                return self.c
        def f2(x+y):
            return x+y
            
        def main():
            o1 = C1()
            print f2(o1.f1(), o1.f1 )
        
        if __name__ == '__main__':
            main()
    ```
* Documentation
    - Add comments to state the 'intent of code'
    - Add doc strings for classes and functions for TA and more importantly, yourself!
    - Always add a note of what type you want your arguments, check using assert!

* Types
    - Python is strongly but dynamically typed
        * Strongly: You can always check the type of a variable
        * Dynamically: that variable name may be changed
    ```
    a = 1
    type(a)
    a = 'abc'
    type(a)
    ```
    - _Just because you could, does not mean you should!_
* Parameterization and Backwards Compatibility
    - Never have constants in your code, PARAMeterize them
    - If you add a new parameter to your function, make it a keyword argument with default value that reflects the previous state

In [14]:
def f1(x):
    return x+1

def f1(x):
    WHY = 1
    return x+WHY
print 'old', f1(1)

def f1(x, y=1):
    return x+y
print 'new', f1(1, y=2)
print 'new', f1(1)

old 2
new 3
new 2


### Git
* Use Git for version control
* Once you make a commit, it can never be lost (until you destroy the repo)
* List of most frequently used commands
  ```bash
  git pull github.com/usrename/repo.git  # pull from a *remote* repo
  # git init                                 # or init a new one
  git pull origin master                 # pull changes from origin to local/master
  git status                             # check modified / new / deleted files
  git add f1.py                          # stage a file to be commited
  git commit -m ""                       # commit all staged files
  git push origin master                 # push to origin, your local master branch
  ```


### Logging
* Have you ever written a print statement inside a loop to debug it?
* Did you comment it out because it was printed too many times?
* Did you remove the comment when you noticed another bug?
* Ever wished your messages had timestamps, name of the class, line number etc?
* Say no more, ```import logging```
* Do not print, use logging module, it is simple and effective!
* Bookmark [Logging Cookbook] and visit when in doubt
* Following is a sample on how to use it
    - to remove the DEBUG line from the output,
    - change the basicConfig from DEBUG to INFO
    - restart ipython notebook
    - run cell again

[Logging Cookbook]: https://docs.python.org/2/howto/logging-cookbook.html

In [15]:
import logging
logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s %(name)-12s %(levelname)-8s %(message)s')
logger = logging.getLogger(__name__)

logger.info('some information')
logger.debug('debug information')
try:
    assert 1==2, 2 
except Exception as e:
    logger.exception(e)
logger.debug('more debug information')

2017-01-28 02:52:12,620 __main__     INFO     some information
2017-01-28 02:52:12,622 __main__     DEBUG    debug information
2017-01-28 02:52:12,624 __main__     ERROR    2
Traceback (most recent call last):
  File "<ipython-input-15-ea7c19b16ac7>", line 9, in <module>
    assert 1==2, 2
AssertionError: 2
2017-01-28 02:52:12,626 __main__     DEBUG    more debug information


# Numpy Basics

In [16]:
import numpy as np

## Arrays
Numpy arrays can be used to represent n-dimensionals arrays, for any arbitrary n.
This notebook demonstrats Vectors (1-d) and Matrices (2-d).

### Vectors

In [17]:
a = np.array([i**2 for i in range(1,51)])
b = np.array([i*1000 for i in range(1,51)])
print a
print type(a),'\n',  a.shape,'\n',  a.size,'\n',  a.dtype, '\n'
print b
print a+b
print b/a

[   1    4    9   16   25   36   49   64   81  100  121  144  169  196  225
  256  289  324  361  400  441  484  529  576  625  676  729  784  841  900
  961 1024 1089 1156 1225 1296 1369 1444 1521 1600 1681 1764 1849 1936 2025
 2116 2209 2304 2401 2500]
<type 'numpy.ndarray'> 
(50,) 
50 
int64 

[ 1000  2000  3000  4000  5000  6000  7000  8000  9000 10000 11000 12000
 13000 14000 15000 16000 17000 18000 19000 20000 21000 22000 23000 24000
 25000 26000 27000 28000 29000 30000 31000 32000 33000 34000 35000 36000
 37000 38000 39000 40000 41000 42000 43000 44000 45000 46000 47000 48000
 49000 50000]
[ 1001  2004  3009  4016  5025  6036  7049  8064  9081 10100 11121 12144
 13169 14196 15225 16256 17289 18324 19361 20400 21441 22484 23529 24576
 25625 26676 27729 28784 29841 30900 31961 33024 34089 35156 36225 37296
 38369 39444 40521 41600 42681 43764 44849 45936 47025 48116 49209 50304
 51401 52500]
[1000  500  333  250  200  166  142  125  111  100   90   83   76   71   66
   62   58   5

### Matrices

In [18]:
a = np.array([[x+y for x in range(5)] for y in range(5)])
b = np.array([[x-y for x in range(5)] for y in range(5)])
print a
print b
print a*b

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]
[[ 0  1  2  3  4]
 [-1  0  1  2  3]
 [-2 -1  0  1  2]
 [-3 -2 -1  0  1]
 [-4 -3 -2 -1  0]]
[[  0   1   4   9  16]
 [ -1   0   3   8  15]
 [ -4  -3   0   5  12]
 [ -9  -8  -5   0   7]
 [-16 -15 -12  -7   0]]


## Some Numpy Functions

In [19]:
a = np.eye(3)
b = np.random.random((3,3))

print 'a:\n',              a
print 'b:\n',              b
print 'a*b:\n',            a*b
print 'np.dot(a,b):\n',    np.dot(a,b)
print 'np.dot(b, b.T):\n', np.dot(b, b.T)

print np.ones((3,3))
print np.zeros((3,3))

a:
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
b:
[[ 0.45844913  0.64152491  0.79392936]
 [ 0.34891338  0.02345215  0.99182992]
 [ 0.27257877  0.00897742  0.71619977]]
a*b:
[[ 0.45844913  0.          0.        ]
 [ 0.          0.02345215  0.        ]
 [ 0.          0.          0.71619977]]
np.dot(a,b):
[[ 0.45844913  0.64152491  0.79392936]
 [ 0.34891338  0.02345215  0.99182992]
 [ 0.27257877  0.00897742  0.71619977]]
np.dot(b, b.T):
[[ 1.25205364  0.96244706  0.69933477]
 [ 0.96244706  1.10601713  0.80566528]
 [ 0.69933477  0.80566528  0.58732189]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


## Utility function to inspect numpy variables

In [20]:
def about(x, LINE=80, SINGLE_LINE=False):
    '''
    author: Yogesh Garg (https://github.com/yogeshg)
    '''
    s ='type:'+str(type(x))+' '
    try:
        s+='shape:'+str(x.shape)+' '
    except Exception as e:
        pass
    try:
        s+='dtype:'+str(x.dtype)+' '
    except Exception as e:
        pass
    try:
        s1 = str(x)
        if(SINGLE_LINE):
            s1 = ' '.join(s1.split('\n'))
            extra = (len(s)+len(s1)) - LINE
            if(extra > 0):
                s1 = s1[:-(extra+3)]+'...'
            s+=s1
        else:
            s+='\n'+s1
    except Exception as e:
        pass
    return s

a = np.eye(3)
print about(a)
print about(a, SINGLE_LINE=True)


type:<type 'numpy.ndarray'> shape:(3, 3) dtype:float64 
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
type:<type 'numpy.ndarray'> shape:(3, 3) dtype:float64 [[ 1.  0.  0.]  [ 0.  ...


## Numpy Types

In [21]:
print about(np.ones((2,2), dtype=np.float))
print about(np.ones((2,2), dtype=np.float32))
print about(np.ones((2,2), dtype=np.float64))
print about(np.ones((2,2), dtype=np.int))
print about(np.ones((2,2), dtype=np.int32))
print about(np.ones((2,2), dtype=np.int64))

type:<type 'numpy.ndarray'> shape:(2, 2) dtype:float64 
[[ 1.  1.]
 [ 1.  1.]]
type:<type 'numpy.ndarray'> shape:(2, 2) dtype:float32 
[[ 1.  1.]
 [ 1.  1.]]
type:<type 'numpy.ndarray'> shape:(2, 2) dtype:float64 
[[ 1.  1.]
 [ 1.  1.]]
type:<type 'numpy.ndarray'> shape:(2, 2) dtype:int64 
[[1 1]
 [1 1]]
type:<type 'numpy.ndarray'> shape:(2, 2) dtype:int32 
[[1 1]
 [1 1]]
type:<type 'numpy.ndarray'> shape:(2, 2) dtype:int64 
[[1 1]
 [1 1]]


## Slicing

In [22]:
a = np.array([[x+y for x in range(5)] for y in range(5)])
b = np.array([[x-y for x in range(5)] for y in range(5)])

print a
print b

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]
[[ 0  1  2  3  4]
 [-1  0  1  2  3]
 [-2 -1  0  1  2]
 [-3 -2 -1  0  1]
 [-4 -3 -2 -1  0]]


### Single row or col as a row

In [23]:
a = np.array([[x+y for x in range(5)] for y in range(5)])

print a[1,:]
print a[:,4]
print a[:,4]

[1 2 3 4 5]
[4 5 6 7 8]
[4 5 6 7 8]


### Multiple rows or cols as a mat

In [24]:
a = np.array([[x+y for x in range(5)] for y in range(5)])

print;print  a[0:2,:]
print;print  a[:,3:5]
print;print  a[:,4:5]  # single col as a 1-col mat


[[0 1 2 3 4]
 [1 2 3 4 5]]

[[3 4]
 [4 5]
 [5 6]
 [6 7]
 [7 8]]

[[4]
 [5]
 [6]
 [7]
 [8]]


### Slicing using lists

In [25]:
a = np.array([[x+y for x in range(5)] for y in range(5)])

print;print a[[0,2,4],:]


[[0 1 2 3 4]
 [2 3 4 5 6]
 [4 5 6 7 8]]


### Slice as an object

In [26]:
a = np.array([[x+y for x in range(5)] for y in range(5)])

print;print a[slice(5),:]
print;print a[slice(0,5),slice(None)]
print;print a[slice(0,5,2),slice(None)]


[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]

[[0 1 2 3 4]
 [2 3 4 5 6]
 [4 5 6 7 8]]


### Slicing using indices

In [27]:
a = np.array([i**2 for i in range(7)])
print a

idx = (a % 4)==1
print idx
print a[idx]

[ 0  1  4  9 16 25 36]
[False  True False  True False  True False]
[ 1  9 25]


## Axes

In [28]:
a = np.array([[x+y for x in range(5)] for y in range(5)])
print a
print a.sum(axis=0)
print a.sum(axis=1)
print a.sum()


[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]
[10 15 20 25 30]
[10 15 20 25 30]
100


## Broadcasting

In [29]:
a = np.array([[x+y for x in range(5)] for y in range(5)])
b = np.array(range(5))
print about(a)
print about(b)
print about(a+b)


type:<type 'numpy.ndarray'> shape:(5, 5) dtype:int64 
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]
type:<type 'numpy.ndarray'> shape:(5,) dtype:int64 
[0 1 2 3 4]
type:<type 'numpy.ndarray'> shape:(5, 5) dtype:int64 
[[ 0  2  4  6  8]
 [ 1  3  5  7  9]
 [ 2  4  6  8 10]
 [ 3  5  7  9 11]
 [ 4  6  8 10 12]]


## What happened?

In [30]:
b2 = np.array([b for i in range(a.shape[1])])
print about(b2)
print about(a+b2)

type:<type 'numpy.ndarray'> shape:(5, 5) dtype:int64 
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
type:<type 'numpy.ndarray'> shape:(5, 5) dtype:int64 
[[ 0  2  4  6  8]
 [ 1  3  5  7  9]
 [ 2  4  6  8 10]
 [ 3  5  7  9 11]
 [ 4  6  8 10 12]]


# References
Following is a set of urls that were referred to while creating this document. You are encouraged to follow these up and read more aabout interesting topics.
* [Homebrew Official](http://brew.sh/)
* [Ipython Tutorial](http://cs231n.github.io/ipython-tutorial/)
* [Numpy Tutorial](http://cs231n.github.io/python-numpy-tutorial/)
* [DL for CV](http://deeplearningforcomputervision.com/)
* [The Hitchhiker’s Guide to Python!](http://docs.python-guide.org/en/latest/)
    - [Virtual Environments Tutorial](http://docs.python-guide.org/en/latest/dev/virtualenvs/#virtualenvironments-ref)
    - [Properly Installing Python](http://docs.python-guide.org/en/latest/starting/installation/)
        - [Installing Python on Mac OS X](http://docs.python-guide.org/en/latest/starting/install/osx/)
    - [Style](http://docs.python-guide.org/en/latest/writing/style/)
* [Tmux Tutorial](https://danielmiessler.com/study/tmux/)
* [Tmux Official](https://tmux.github.io/)
* [The Python Tutorial](https://docs.python.org/2.7/tutorial/)
    - [Logging](https://docs.python.org/2/howto/logging-cookbook.html)
    - [Collections](https://docs.python.org/2/library/collections.html)
    - [Functional Programming Tools](https://docs.python.org/2/tutorial/datastructures.html#functional-programming-tools)
* [Git Official](https://git-scm.com/)
* [VirtualEnv Official](https://virtualenv.pypa.io/en/stable/)

<!-- http://cs231n.github.io/aws-tutorial/ -->
<!-- http://cs231n.github.io/terminal-tutorial/ -->
